services:
  mysql:
    image: mysql:8.4
    container_name: oil_news_mysql
    environment:
      MYSQL_ROOT_PASSWORD: change-me
      MYSQL_DATABASE: oil_news_project
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
